import { Company, Person, Receipt, Profile } from '@/types/database';

export const DEMO_PROFILE: Profile = {
  id: 'usr-demo-001',
  full_name: 'Elias Espinoza',
  email: 'eleliasespinoza@hotmail.com',
  role: 'owner',
  avatar_url: null,
  created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-01T00:00:00Z',
};

export const DEMO_COMPANIES: Company[] = [
  {
    id: 'comp-syss-001',
    name: 'Soluciones y Sistemas de Seguridad',
    business_name: 'SOLUCIONES Y SISTEMAS DE SEGURIDAD S.A. DE C.V.',
    rfc: 'SSS180412XX1',
    tax_regime: '601 - General de Ley Personas Morales',
    address: 'Calle Los Olivos #711, Colonia Kennedy, Nogales, Sonora',
    phone: '+52 631 115 7032',
    whatsapp: '+52 631 115 7032',
    email: 'eleliasespinoza@hotmail.com',
    website: 'www.sysseguridad.com.mx',
    logo_url: '/logo-syss.png',
    slogan: 'INNOVACIÓN • CONFIANZA • PROTECCIÓN',
    primary_color: '#0b192c',
    secondary_color: '#334155',
    accent_color: '#00a8cc',
    folio_prefix: 'SYSS',
    next_folio_number: 790,
    signer_name: 'Lic. Karla Hernández López',
    signer_role: 'Gerente de Administración',
    signer_signature_url: null,
    paper_size: 'letter_landscape',
    currency: 'MXN',
    timezone: 'America/Hermosillo',
    legal_disclaimer: 'Este documento es un comprobante administrativo interno y no sustituye un CFDI de nómina timbrado.',
    show_header: true,
    show_footer: true,
    show_payment_info: true,
    show_qr_validation: true,
    show_signature: true,
    created_by: 'usr-demo-001',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-05-15T00:00:00Z',
  },
  {
    id: 'comp-tech-002',
    name: 'NovaTech Consultoría',
    business_name: 'NOVATECH SOFTWARE & DIGITAL S.A.P.I. DE C.V.',
    rfc: 'NSD210905AB3',
    tax_regime: '601 - General de Ley Personas Morales',
    address: 'Av. Paseo de la Reforma 404, Piso 8, Ciudad de México',
    phone: '+52 55 8421 9000',
    whatsapp: '+52 55 8421 9000',
    email: 'contacto@novatech.mx',
    website: 'www.novatech.mx',
    logo_url: null,
    slogan: 'TRANSFORMACIÓN DIGITAL ÁGIL',
    primary_color: '#1e1b4b',
    secondary_color: '#3b82f6',
    accent_color: '#6366f1',
    folio_prefix: 'NOVA',
    next_folio_number: 101,
    signer_name: 'Ing. Roberto Méndez Cruz',
    signer_role: 'Director de Operaciones',
    signer_signature_url: null,
    paper_size: 'letter_landscape',
    currency: 'MXN',
    timezone: 'America/Mexico_City',
    legal_disclaimer: 'Este documento es un comprobante administrativo interno y no sustituye un CFDI de nómina timbrado.',
    show_header: true,
    show_footer: true,
    show_payment_info: true,
    show_qr_validation: true,
    show_signature: true,
    created_by: 'usr-demo-001',
    created_at: '2024-02-01T00:00:00Z',
    updated_at: '2024-05-01T00:00:00Z',
  }
];

export const DEMO_PEOPLE: Person[] = [
  {
    id: 'per-001',
    company_id: 'comp-syss-001',
    person_type: 'collaborator',
    full_name: 'María Fernanda Ríos Martínez',
    internal_id: 'COL-0184',
    department: 'Ingeniería',
    position: 'Coordinador de Proyectos',
    rfc: 'RIMM920715MDFRNR06',
    curp: 'RIMM920715MDFRN06',
    nss: '12948291041',
    contract_type: 'Sueldos y Salarios e Ingresos Asimilados a Salarios',
    phone: '+52 631 555 1234',
    email: 'm.rios@sysseguridad.com.mx',
    address: 'Av. Álvaro Obregón #450, Nogales, Son.',
    bank_name: 'Santander',
    bank_account_masked: '•••• 6712',
    clabe_masked: '•••• •••• •••• 6712',
    hire_date: '2022-03-01',
    status: 'active',
    internal_notes: 'Líder técnico en implementaciones de control de acceso.',
    created_by: 'usr-demo-001',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-05-15T00:00:00Z',
  },
  {
    id: 'per-002',
    company_id: 'comp-syss-001',
    person_type: 'worker',
    full_name: 'Carlos Alberto Valenzuela Soto',
    internal_id: 'TEC-0042',
    department: 'Operaciones de Campo',
    position: 'Técnico Especialista en CCTV',
    rfc: 'VASC881120AB9',
    curp: 'VASC881120HSONTL02',
    nss: '43928172635',
    contract_type: 'Tiempo Indeterminado',
    phone: '+52 631 555 5678',
    email: 'carlos.valenzuela@sysseguridad.com.mx',
    address: 'Calle Ruiz Cortines #12, Nogales, Son.',
    bank_name: 'BBVA',
    bank_account_masked: '•••• 4390',
    clabe_masked: '•••• •••• •••• 4390',
    hire_date: '2021-08-15',
    status: 'active',
    internal_notes: 'Turno mixto con certificaciones en fibra óptica.',
    created_by: 'usr-demo-001',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-05-15T00:00:00Z',
  },
  {
    id: 'per-003',
    company_id: 'comp-tech-002',
    person_type: 'collaborator',
    full_name: 'Sofía Daniela Garza Morales',
    internal_id: 'DEV-009',
    department: 'Desarrollo Frontend',
    position: 'Senior UI/UX Engineer',
    rfc: 'GAMS950410XX2',
    curp: 'GAMS950410MNLSRR09',
    nss: '98765432101',
    contract_type: 'Honorarios Profesionales',
    phone: '+52 55 1234 5678',
    email: 'sofia.garza@novatech.mx',
    address: 'Col. Condesa, CDMX',
    bank_name: 'Banorte',
    bank_account_masked: '•••• 8821',
    clabe_masked: '•••• •••• •••• 8821',
    hire_date: '2023-01-10',
    status: 'active',
    internal_notes: 'Desarrollo en Next.js y React.',
    created_by: 'usr-demo-001',
    created_at: '2024-02-01T00:00:00Z',
    updated_at: '2024-05-01T00:00:00Z',
  }
];

export const DEMO_RECEIPTS: Receipt[] = [
  {
    id: 'rec-syss-0789',
    company_id: 'comp-syss-001',
    person_id: 'per-001',
    receipt_type: 'payroll',
    folio: 'SYSS-2405-0789',
    internal_folio: 'SYSSINT-015-0789',
    issue_date: '2024-05-15',
    payment_date: '2024-05-15',
    period_start: '2024-05-01',
    period_end: '2024-05-15',
    frequency: 'biweekly',
    status: 'paid',
    currency: 'MXN',
    payment_method: 'bank_transfer',
    bank_name: 'Santander',
    bank_account_masked: '•••• 6712',
    deposit_date: '2024-05-15',
    verification_code: 'K3JL-9Q7R-D6EK',
    signer_name: 'Lic. Karla Hernández López',
    signer_role: 'Gerente de Administración',
    signer_signature_url: null,
    notes: 'Pago quincenal ordinario correspondiente a la primera quincena de Mayo 2024.',
    total_earnings: 18000.00,
    total_deductions: 5964.95,
    net_total: 12035.05,
    created_by: 'usr-demo-001',
    created_at: '2024-05-15T10:00:00Z',
    updated_at: '2024-05-15T12:00:00Z',
    company: DEMO_COMPANIES[0],
    person: DEMO_PEOPLE[0],
    earnings: [
      { id: 'ear-001', concept: 'Sueldo Base', reference: '15.00 días', amount: 14000.00, display_order: 1 },
      { id: 'ear-002', concept: 'Bonificación por Desempeño', reference: 'Quincenal', amount: 2800.00, display_order: 2 },
      { id: 'ear-003', concept: 'Vales de Despensa', reference: 'Evento', amount: 700.00, display_order: 3 },
      { id: 'ear-004', concept: 'Ayuda de Transporte', reference: 'Evento', amount: 500.00, display_order: 4 },
    ],
    deductions: [
      { id: 'ded-001', concept: 'ISR', reference: 'Artículo 96 LISR', amount: 2482.80, display_order: 1 },
      { id: 'ded-002', concept: 'IMSS', reference: 'Trabajador', amount: 482.15, display_order: 2 },
      { id: 'ded-003', concept: 'Infonavit', reference: 'Crédito', amount: 2600.00, display_order: 3 },
      { id: 'ded-004', concept: 'Fondo de Ahorro', reference: 'Contrato', amount: 400.00, display_order: 4 },
    ],
  },
  {
    id: 'rec-syss-0790',
    company_id: 'comp-syss-001',
    person_id: 'per-002',
    receipt_type: 'payroll',
    folio: 'SYSS-2405-0790',
    internal_folio: 'SYSSINT-015-0790',
    issue_date: '2024-05-15',
    payment_date: '2024-05-15',
    period_start: '2024-05-01',
    period_end: '2024-05-15',
    frequency: 'biweekly',
    status: 'paid',
    currency: 'MXN',
    payment_method: 'bank_transfer',
    bank_name: 'BBVA',
    bank_account_masked: '•••• 4390',
    deposit_date: '2024-05-15',
    verification_code: 'M8XP-4B2Q-99TY',
    signer_name: 'Lic. Karla Hernández López',
    signer_role: 'Gerente de Administración',
    signer_signature_url: null,
    notes: 'Pago de nómina ordinaria quincenal con horas extras de campo.',
    total_earnings: 11500.00,
    total_deductions: 2150.00,
    net_total: 9350.00,
    created_by: 'usr-demo-001',
    created_at: '2024-05-15T11:00:00Z',
    updated_at: '2024-05-15T12:30:00Z',
    company: DEMO_COMPANIES[0],
    person: DEMO_PEOPLE[1],
    earnings: [
      { id: 'ear-101', concept: 'Sueldo Base', reference: '15.00 días', amount: 9500.00, display_order: 1 },
      { id: 'ear-102', concept: 'Horas Extras', reference: '12 hrs', amount: 1500.00, display_order: 2 },
      { id: 'ear-103', concept: 'Bono de Puntualidad', reference: 'Quincenal', amount: 500.00, display_order: 3 },
    ],
    deductions: [
      { id: 'ded-101', concept: 'ISR', reference: 'Artículo 96 LISR', amount: 1450.00, display_order: 1 },
      { id: 'ded-102', concept: 'IMSS', reference: 'Trabajador', amount: 350.00, display_order: 2 },
      { id: 'ded-103', concept: 'Fondo de Ahorro', reference: 'Contrato', amount: 350.00, display_order: 3 },
    ],
  }
];
